<h3>Lista de galerias</h3>
<p>
    <a class="btn btn-success" href="<?php echo $this->baseUrl('adm/galerias/add'); ?>">Adicionar galeria</a>
</p>
<?php if (count($this->rows) > 0): ?>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Miniatura</th>
                <th>titulo</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            <?php
            foreach ($this->rows as $row):
                $id = $row->galeria_id;
                $img = $row->galeria_img_capa;
                ?>
                <tr>
                    <td>
                        <?php if (!file_exists($this->baseUrl('/galerias/' . $id . '/fotosD/' . $img)) || empty($img)): ?>
                            <img src="<?php echo $this->baseUrl('img/no_iPhoto.png'); ?>" width="155px" height="155px" alt="Sem Imagem Capa" title="Sem Imagem Capa"/>
                        <?php else: ?>
                            <img src="<?php echo $this->baseUrl('/galerias/' . $id . '/fotosD/' . $img); ?>" alt="">
                        <?php endif; ?>
                    </td>
                    <td><?php echo $row->galeria_titulo; ?></td>
                    <td>
                        <a class="btn btn-primary" href="<?php echo $this->baseUrl('adm/galerias/edit/id/' . $id); ?>"><i class="icon-search"></i></a>
                        <a class="btn btn-success" href="<?php echo $this->baseUrl('adm/galeriasimagens/upload/id/' . $id); ?>"><i class="icon-search"></i></a>
                        <a class="btn btn-info" href="<?php echo $this->baseUrl('adm/galeriasimagens/index/id/' . $id); ?>"><i class="icon-search"></i></a>
                        <a onclick="return confirm('Você tem certeza que quer apagar?')" class="btn btn-danger" href="<?php echo $this->baseUrl('adm/galerias/delete/id/' . $id); ?>">Apagar</a>
                    </td>
                </tr>
            <?php endforeach; ?>
        <tbody>
    </table>
<?php else: ?>
    <p class="alert alert-info">Não há galerias cadastradas.</p>
<?php endif; ?><p>