<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>GilcierWeb</title>  
        <?php echo $this->headLink()->appendStylesheet($this->baseUrl() . '/css/bootstrap.min.css') ?>
        <?php echo $this->headLink()->appendStylesheet($this->baseUrl() . '/css/adm/estilos.css') ?>
    </head>
    <body>
        
        <?php echo $this->render('partials/adm/menu.phtml'); ?>

        <div class="container-fluid">

            <div class="row-fluid">

                <div class="span3">
                    <div class="well sidebar-nav">
                        <ul class="nav nav-list">
                            <li class="nav-header">Sidebar</li>
                            <li class="active"><a href="#">Link</a></li>
                            <li><a href="#">Link</a></li>
                            <li><a href="#">Link</a></li>
                            <li><a href="#">Link</a></li>
                            <li class="nav-header">Sidebar</li>
                            <li><a href="#">Link</a></li>
                            <li><a href="#">Link</a></li>
                            <li><a href="#">Link</a></li>
                            <li><a href="#">Link</a></li>
                            <li><a href="#">Link</a></li>
                            <li><a href="#">Link</a></li>
                            <li class="nav-header">Sidebar</li>
                            <li><a href="#">Link</a></li>
                            <li><a href="#">Link</a></li>
                            <li><a href="#">Link</a></li>
                        </ul>
                    </div><!--/.well -->
                </div><!--/span-->


                <div class="span9">
                    <div class="row-fluid">
                        <?php if (isset($this->flashMessenger[0]['success']) && !empty($this->flashMessenger[0]['success'])): ?>
                            <div class="alert alert-success"><a href="#" class="close" data-dismiss="alert">×</a>
                                <?php echo $this->flashMessenger[0]['success']; ?></div>
                        <?php endif; ?>
                        <?php if (isset($this->flashMessenger[0]['error']) && !empty($this->flashMessenger[0]['error'])): ?>
                            <div class="alert alert-error"><a href="#" class="close" data-dismiss="alert">×</a>
                                Error: <?php echo $this->flashMessenger[0]['error']; ?></div>
                        <?php endif; ?>


                        <?php echo $this->layout()->content; ?>

                    </div>
                </div>

            </div>

            <div class="row-fluid">
                <div class="span12">
                    <hr />  
                    <footer>
                        <p>Desenvolvido por: GilcierWeb - <small>Versão: 1.0 - <?php echo date('Y'); ?></small></p>
                        <p>Site melhor visualizado com navegadores modernos como: 
                            <a href="http://www.baixaki.com.br/download/mozilla-firefox.htm" title="Mozilla Firefox" target="_blank">Firefox</a>,
                            <a href="http://www.baixaki.com.br/download/opera.htm" title="Opera" target="_blank">Opera</a>,
                            <a href="http://www.baixaki.com.br/download/google-chrome.htm" title="Google Chrome" target="_blank">Chorme</a>, <a href="http://www.baixaki.com.br/download/safari.htm" title="Apple Safari" target="_blank">Apple Safari</a>
                        </p>
                    </footer>
                </div>
            </div><!--/row-fluid-->

        </div>

        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js" type="text/javascript"></script>
        <script>
            window.jQuery || document.write('<script src="<?php echo $this->baseUrl(); ?>/js/jquery-1.10.2.min.js">\x3c/script>')
        </script>
        <script src="<?php echo $this->baseUrl(); ?>/js/bootstrap.min.js" type="text/javascript"></script>
        <?php echo $this->render('partials/adm/js_all_adm.phtml'); ?>
    </body>
</html>