<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>GilcierWeb</title>  
        <?php echo $this->headLink()->appendStylesheet($this->baseUrl() . '/css/bootstrap.min.css') ?>
        <?php echo $this->headLink()->appendStylesheet($this->baseUrl() . '/css/estilos.css') ?>
    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container-fluid">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="#">GilcierWeb</a>
                    <div class="nav-collapse collapse">                       
                        <ul class="nav">
                            <li class="active"><a href="<?php echo $this->baseUrl('adm'); ?>">Home</a></li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Produtos <b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li><a href="<?php echo $this->baseUrl('adm/produtos'); ?>">Listar</a></li>
                                    <li><a href="<?php echo $this->baseUrl('adm/produtos/add'); ?>">Adicionar</a></li>
                                    <li><a href="#">Another action</a></li>
                                    <li><a href="#">Something else here</a></li>
                                    <li class="divider"></li>
                                    <li class="nav-header">Nav header</li>
                                    <li><a href="#">Separated link</a></li>
                                    <li><a href="#">One more separated link</a></li>
                                </ul>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Categorias<b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li><a href="<?php echo $this->baseUrl('adm/categorias'); ?>">Listar</a></li>
                                    <li><a href="<?php echo $this->baseUrl('adm/categorias/add'); ?>">Adicionar</a></li>
                                    <li class="divider"></li>
                                    <li class="nav-header">Subcategorias</li>
                                    <li><a href="<?php echo $this->baseUrl('adm/subcategorias'); ?>">Listar</a></li> 
                                    <li><a href="<?php echo $this->baseUrl('adm/subcategorias/add'); ?>">Adicionar</a></li>                                   
                                </ul>
                            </li>
                            <li><a href="#about">About</a></li>
                            <li><a href="#about">About</a></li>
                            <li><?php // echo Html::anchor('adm/videos', 'Vídeos');                                     ?></li>
                            <li><a href="#contact">ContatO</a></li>
                        </ul>
                        <p class="navbar-text pull-right">
                            Logged in as <a href="#" class="navbar-link">Username</a>
                        </p>
                    </div><!--/.nav-collapse -->
                </div>
            </div>
        </div>

        <div class="container-fluid">
            <div class="row-fluid">
                <div class="hero-unit">
                    <h1 class="">Special Offer</h1>
                    <p class="">here is the best offer of the month! Do not loose it!</p>
                    <p><a href="#" class="btn btn-primary btn-large">Learn more »</a></p>
                </div>
            </div>

            <div class="row-fluid">

                <div class="span9">

                    <div class="row-fluid">
                        <?php if (isset($this->flashMessenger[0]['success']) && !empty($this->flashMessenger[0]['success'])): ?>
                            <div class="alert alert-success"><a href="#" class="close" data-dismiss="alert">×</a>
                                <?php echo $this->flashMessenger[0]['success']; ?></div>
                        <?php endif; ?>
                        <?php if (isset($this->flashMessenger[0]['error']) && !empty($this->flashMessenger[0]['error'])): ?>
                            <div class="alert alert-error"><a href="#" class="close" data-dismiss="alert">×</a>
                                Error: <?php echo $this->flashMessenger[0]['error']; ?></div>
                        <?php endif; ?>


                        <?php echo $this->layout()->content; ?>

                    </div>

                </div>

                <div class="span3">

                    <div class="well">
                        <ul class="nav nav-list">
                            <li class="nav-header">Sidebar</li>
                            <li class="active">
                                <a href="#">Link</a>
                            </li>
                            <li>
                                <a href="#">Link</a>
                            </li>
                            <li>
                                <a href="#">Link</a>
                            </li>

                            <li class="nav-header">Sidebar</li>
                            <li>
                                <a href="#">Link</a>
                            </li>
                            <li>
                                <a href="#">Link</a>
                            </li>
                            <li>
                                <a href="#">Link</a>
                            </li>

                            <li class="nav-header">Sidebar</li>
                            <li>
                                <a href="#">Link</a>
                            </li>
                            <li>
                                <a href="#">Link</a>
                            </li>
                            <li>
                                <a href="#">Link</a>
                            </li>
                        </ul>
                    </div>

                    <div class="well">
                        <h4>Filters</h4>
                        <form>
                            <label class="checkbox">
                                <input type="checkbox" value="">
                                Filter 1
                            </label>

                            <label class="checkbox">
                                <input type="checkbox" value="">
                                Filter 1
                            </label>

                            <label class="checkbox">
                                <input type="checkbox" value="">
                                Filter 1
                            </label>

                            <label class="checkbox">
                                <input type="checkbox" value="">
                                Filter 1
                            </label>
                            <button class="btn btn-primary pull-right" type="submit">Filter</button>
                        </form>
                    </div>

                    <div class="well">
                        <h4>Sort</h4>
                        <form>
                            <label class="radio">
                                <input type="radio" name="optionsRadios" id="optionsRadios1" value="option1" checked>
                                Sort 1
                            </label>
                            <label class="radio">
                                <input type="radio" name="optionsRadios" id="optionsRadios2" value="option2">
                                Sort 2
                            </label>
                            <button class="btn btn-primary pull-right" type="submit">Sort</button>
                        </form>
                    </div>

                    <div class="well">
                        <form class="form login-form">
                            <h2>Sign in</h2>
                            <div>
                                <label>Username</label>
                                <input id="Username" name="Username" type="text" />

                                <label>Password</label>
                                <input id="Password" name="Password" type="password" />

                                <label class="checkbox inline">
                                    <input type="checkbox" id="RememberMe" value="option1"> Remember me
                                </label>

                                <br /><br />

                                <button type="submit" class="btn btn-success">Login</button>
                            </div>
                            <br />
                            <a href="#">register</a>&nbsp;&#124;&nbsp;<a href="#">forgot password?</a>
                        </form>
                    </div>
                </div>

            </div><!--/span-->



            <div class="row-fluid">

               <div class="span4">
                    <h4>Info</h4>
                    <ul class="nav nav-stacked">
                        <li><a href="#">Sell Conditions</a>
                        <li><a href="#">Shipping Costs</a>
                        <li><a href="#">Shipping Conditions</a>
                        <li><a href="#">Returns</a>
                        <li><a href="#">About Us</a>
                    </ul>
                </div> 

                <div class="span4">
                    <h4>Location and Contacts</h4>
                    <p><i class="icon-map-marker"></i>&nbsp;I do not Know Avenue, A City</p>
                    <p><i class="icon-phone"></i>&nbsp;Phone: 234 739.126.72</p>
                    <p><i class="icon-print"></i>&nbsp;Fax: 213 123.12.090</p>
                    <p><i class="icon-envelope"></i>&nbsp;Email: info@mydomain.com</p>
                    <p><i class="icon-globe"></i>&nbsp;Web: http://www.mydomain.com</p>
                </div>

                <div class="span4">
                    <h4>Newsletter</h4>
                    <p>Write you email to subscribe to our Newsletter service. Thanks!</p>
                    <form class="form-newsletter">
                        <div class="input-append">
                            <input type="email" class="span2" placeholder="your email">
                            <button type="submit" class="btn">Subscribe</button>
                        </div>
                    </form>
                </div>

                <div class="span12">
                    <hr />  
                    <footer>
                        <p>Desenvolvido por: GilcierWeb - <small>Versão: 1.0 - <?php echo date('Y'); ?></small></p>
                        <p>Site melhor visualizado com navegadores modernos como: 
                            <a href="http://www.baixaki.com.br/download/mozilla-firefox.htm" title="Mozilla Firefox" target="_blank">Firefox</a>,
                            <a href="http://www.baixaki.com.br/download/opera.htm" title="Opera" target="_blank">Opera</a>,
                            <a href="http://www.baixaki.com.br/download/google-chrome.htm" title="Google Chrome" target="_blank">Chorme</a>, <a href="http://www.baixaki.com.br/download/safari.htm" title="Apple Safari" target="_blank">Apple Safari</a>
                        </p>
                    </footer>
                </div>
            </div><!--/row-fluid-->

        </div>

        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js" type="text/javascript"></script>
        <script>
            window.jQuery || document.write('<script src="<?php echo $this->baseUrl(); ?>/js/jquery-1.10.2.min.js">\x3c/script>')
        </script>
        <script src="<?php echo $this->baseUrl(); ?>/js/bootstrap.min.js" type="text/javascript"></script>
        <?php echo $this->render('partials/site/js_all.phtml'); ?>
    </body>
</html>
