<h2>Lista de marcas</h2>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>Categoria</th>
            <th>Descrição</th>
            <th>Ações</th>
        </tr>
    </thead>
    <tbody>
        <?php
        foreach ($this->rows as $row) :
            $id = $row->marca_id;
            ?>
            <tr>
                <td><?php echo $row->marca_titulo; ?></td>
                <td><?php echo $row->marca_titulo; ?></td>
                <td>
                    <a class="btn btn-primary" href="<?php echo $this->baseUrl('adm/marcas/edit/id/' . $id); ?>"><i class="icon-search"></i></a>
                    <a onclick="return confirm('Você tem certeza que quer apagar?')" class="btn btn-danger" href="<?php echo $this->baseUrl('adm/marcas/delete/id/' . $id); ?>">Apagar</a>
                </td>
            </tr>
        <?php endforeach; ?>
    <tbody>
</table>

